-- burns everything slow and steady (use it at least 3 times to be sure everything is dead...)
ALTER TABLE MITFAHRER
DROP CONSTRAINT MITFAHRER_FK2;
DROP TABLE MITFAHRER;

ALTER TABLE VERBINDUNG
DROP CONSTRAINT VERBINDUNG_PK;
ALTER TABLE VERBINDUNG
DROP CONSTRAINT VERBINDUNG_FK1;
ALTER TABLE VERBINDUNG
DROP CONSTRAINT VERBINDUNG_FK2;
ALTER TABLE VERBINDUNG
DROP CONSTRAINT VERBINDUNG_CHK1;
ALTER TABLE VERBINDUNG
DROP CONSTRAINT VERBINDUNG_CHK2;
ALTER TABLE VERBINDUNG
DROP CONSTRAINT VERBINDUNG_CHK3;
DROP TABLE VERBINDUNG;

ALTER TABLE STRECKE
DROP CONSTRAINT STRECKE_PK;
ALTER TABLE STRECKE
DROP CONSTRAINT STRECKE_CHK1;
ALTER TABLE STRECKE
DROP CONSTRAINT STRECKE_FK1;
DROP TABLE STRECKE;

ALTER TABLE ZUG
DROP CONSTRAINT ZUG_PK;
ALTER TABLE ZUG
DROP CONSTRAINT ZUG_CHK1;
ALTER TABLE ZUG
DROP CONSTRAINT ZUG_CHK2;
DROP TABLE ZUG;

ALTER TABLE HALTESTELLE
DROP CONSTRAINT HALTESTELLE_PK;
ALTER TABLE HALTESTELLE
DROP CONSTRAINT HALTESTELLE_CHK1;
ALTER TABLE HALTESTELLE
DROP CONSTRAINT HALTESTELLE_CHK2;
DROP TABLE HALTESTELLE;

DROP TABLE URLAUB;

ALTER TABLE MITARBEITER
DROP CONSTRAINT MITARBEITER_PK;
ALTER TABLE MITARBEITER
DROP CONSTRAINT MITARBEITER_CHK1;
ALTER TABLE MITARBEITER
DROP CONSTRAINT MITARBEITER_CHK2;
ALTER TABLE MITARBEITER
DROP CONSTRAINT MITARBEITER_CHK3;
ALTER TABLE MITARBEITER
DROP CONSTRAINT MITARBEITER_CHK4;
DROP TABLE MITARBEITER;


DROP VIEW ALLE_STOPS_V;